import = [ 
  "~/.config/alacritty/catppuccin-latte.toml"
  #"~/.config/alacritty/catppuccin-mocha.toml"
]

[font]
# normal = { family = "FiraCode Nerd Font", style = "Regular" }
normal = { family = "Hack Nerd Font Mono", style = "Regular" }
size = 12

[env]
TERM = "xterm-256color"

[window]
option_as_alt = "Both"
decorations = "None"

[selection]
save_to_clipboard = true

[keyboard]
bindings = [
  { key = "C", mods = "Alt", action = "Copy" },
  { key = "V", mods = "Alt", action = "Paste" }
]

[mouse]
bindings = [
  { mouse = "Right", action = "Paste" },
]
