import = [ 
  #"~/.config/alacritty/catppuccin-latte.toml"
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[font]
normal = { family = "Hack Nerd Font Mono", style = "Regular" }
size = 14

[env]
TERM = "xterm-256color"

[window]
option_as_alt = "Both"
decorations = "None"

